require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  Exclude:
    - bin/**/*
    - spec/spec_helper.rb
    - vendor/**/*
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
RSpec/ExampleLength:
  Max: 20
RSpec/MultipleExpectations:
  Enabled: false

inherit_from: .rubocop_todo.yml
