# frozen_string_literal: true

source "https://rubygems.org"

ruby File.open(".ruby-version", "rb") { |f| f.read.chomp }

gem "awesome_print"
gem "pry", "~> 0.12.0"
gem "rspec", "~> 3.8.0"
gem "rubocop", "~> 1.69.2"
gem "rubocop-rake", "~> 0.6.0"
gem "rubocop-rspec", "~> 3.2.0"
