AllCops:
  Exclude:
    - bin/**/*
    - spec/spec_helper.rb
    - vendor/**/*
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*

inherit_from: .rubocop_todo.yml
