AllCops:
  Exclude:
    - bin/**/*
    - spec/spec_helper.rb
    - vendor/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false

inherit_from: .rubocop_todo.yml
