# frozen_string_literal: true

source 'https://rubygems.org'

ruby File.open('.ruby-version', 'rb') { |f| f.read.chomp }

gem 'awesome_print'

gem 'guard'
gem 'guard-rspec', require: false

gem 'pry', '~> 0.15.0'

gem 'rake', '~> 13.2'
gem 'rspec', '~> 3.13.0'
gem 'rubocop', '~> 1.69.0'
gem 'rubocop-rake', '0.6.0', require: false
gem 'rubocop-rspec', '3.2.0', require: false
