name: setup ruby
description: setup ruby
inputs:
  working-directory:
    description: directory to use
    required: true
runs:
  using: composite
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
