name: 2021-ruby

on:
  pull_request:
  push:
    branches: [master]
    paths:
        - 2021/ruby/**

defaults:
  run:
    working-directory: ./2021/ruby

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: debug
        run: pwd
      - name: Setup Ruby
        uses: ./.github/shared/setup
      - name: Run rubocop
        run: bundle exec rubocop
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ./.github/shared/setup
      - name: Run tests
        run: bundle exec rspec
