name: 2024-ruby

on:
  pull_request:
  push:
    branches: [master]
    paths:
        - 2024/ruby/**

defaults:
  run:
    working-directory: ./2024/ruby

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run tests
      run: bundle exec rspec
