name: 2024-ruby

on:
  pull_request:
  push:
    paths:
        - 2024/ruby/**

defaults:
  run:
    working-directory: ./2024/ruby

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/shared/setup
      - name: Run rubocop
        run: bundle exec rubocop
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/shared/setup
      - name: Run tests
        run: bundle exec rspec
