name: 2024-ruby

on:
  pull_request:
  push:
    paths:
        - 2024/ruby/**

defaults:
  run:
    working-directory: ./2024/ruby

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: "./.github/shared/setup"
    - name: RuboCop Linter Action
      uses: andrewmcodes/rubocop-linter-action@v3.3.0
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: "./.github/shared/setup"
    - name: Run tests
      run: bundle exec rspec
